name: go_router_autogen
description: Generate go_router routes from @RoutePage() annotations with zero manual paths/names.
version: 0.0.7
repository: https://github.com/neotin695/go_router_generator_plus
issue_tracker: https://github.com/neotin695/go_router_generator_plus/issues
homepage: https://github.com/neotin695/go_router_generator_plus

environment:
   sdk: ^3.8.1

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  go_router: ^14.2.0
  meta: ^1.12.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^5.0.0
