name: go_router_generator_plus
description: Generate go_router routes from @RoutePage() annotations with zero manual paths/names.
version: 0.0.1
repository: https://github.com/neotin695/go_router_generator_plus
issue_tracker: https://github.com/neotin695/go_router_generator_plus/issues
homepage: https://github.com/neotin695/go_router_generator_plus

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  go_router: ^14.2.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0

flutter:
